[package]
name = "mdc-desktop"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tokio = { workspace = true }
anyhow = { workspace = true }
mdc-core = { path = "../../crates/mdc-core" }
