[package]
name = "mdc-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mdc-server"
path = "src/main.rs"

[dependencies]
mdc-core = { path = "../mdc-core" }
reqwest = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
jsonwebtoken = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true }
